use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct StatsJsonEntry {
    #[serde(rename = "TOTAL_UNITS_HEALED")]
    pub total_units_healed: Option<i64>,
    #[serde(rename = "HoL_Elite_KaiSaKillerInstinctKills")]
    pub ho_l_elite_kai_sa_killer_instinct_kills: Option<i64>,
    #[serde(rename = "S3A1_Takedowns")]
    pub s3_a1_takedowns: Option<i64>,
    #[serde(rename = "HoL_KillsWhileLowHealth")]
    pub ho_l_kills_while_low_health: Option<i64>,
    #[serde(rename = "SPELL2_CAST")]
    pub spell2_cast: Option<i64>,
    #[serde(rename = "Missions_Crepe_TakedownsWithInhibBuff")]
    pub missions_crepe_takedowns_with_inhib_buff: Option<i64>,
    #[serde(rename = "PING")]
    pub ping: Option<i64>,
    #[serde(rename = "NEUTRAL_MINIONS_KILLED_ENEMY_JUNGLE")]
    pub neutral_minions_killed_enemy_jungle: Option<i64>,
    #[serde(rename = "PUSH_PINGS")]
    pub push_pings: Option<i64>,
    #[serde(rename = "MAGIC_DAMAGE_DEALT_TO_CHAMPIONS")]
    pub magic_damage_dealt_to_champions: Option<i64>,
    #[serde(rename = "2026_S1A1_SR_RoleQuestComplete")]
    pub field_2026_s1_a1_sr_role_quest_complete: Option<i64>,
    #[serde(rename = "NODE_NEUTRALIZE_ASSIST")]
    pub node_neutralize_assist: Option<i64>,
    #[serde(rename = "PERK0_VAR2")]
    pub perk0_var2: Option<i64>,
    #[serde(rename = "OBJECTIVES_STOLEN")]
    pub objectives_stolen: Option<i64>,
    #[serde(rename = "GOLD_SPENT")]
    pub gold_spent: Option<i64>,
    #[serde(rename = "PLAYER_SCORE_11")]
    pub player_score_11: Option<i64>,
    #[serde(rename = "PERK4_VAR2")]
    pub perk4_var2: Option<i64>,
    #[serde(rename = "S3A1_Event_DoombotsTakenDownBefore5")]
    pub s3_a1_event_doombots_taken_down_before5: Option<i64>,
    #[serde(rename = "TRIPLE_KILLS")]
    pub triple_kills: Option<i64>,
    #[serde(rename = "Missions_BXP_EarnedPerGame")]
    pub missions_bxp_earned_per_game: Option<i64>,
    #[serde(rename = "ATAKHAN_KILLS")]
    pub atakhan_kills: Option<i64>,
    #[serde(rename = "PLAYER_AUGMENT_6")]
    pub player_augment_6: Option<i64>,
    #[serde(rename = "ALL_IN_PINGS")]
    pub all_in_pings: Option<i64>,
    #[serde(rename = "LARGEST_ATTACK_DAMAGE")]
    pub largest_attack_damage: Option<i64>,
    #[serde(rename = "Missions_TakedownEpicMonsters")]
    pub missions_takedown_epic_monsters: Option<i64>,
    #[serde(rename = "TOTAL_HEAL")]
    pub total_heal: Option<i64>,
    #[serde(rename = "2026_S1A1_SR_FaerieWards")]
    pub field_2026_s1_a1_sr_faerie_wards: Option<i64>,
    #[serde(rename = "2026_S1A1_Skins_Ziggs")]
    pub field_2026_s1_a1_skins_ziggs: Option<i64>,
    #[serde(rename = "Event_S1_A2_Arena_NoxianChampions")]
    pub event_s1_a2_arena_noxian_champions: Option<i64>,
    #[serde(rename = "DemonsHand_MissionPointsC")]
    pub demons_hand_mission_points_c: Option<i64>,
    #[serde(rename = "GAME_ENDED_IN_SURRENDER")]
    pub game_ended_in_surrender: Option<i64>,
    #[serde(rename = "TOTAL_DAMAGE_DEALT_TO_TURRETS")]
    pub total_damage_dealt_to_turrets: Option<i64>,
    #[serde(rename = "LONGEST_TIME_SPENT_LIVING")]
    pub longest_time_spent_living: Option<i64>,
    #[serde(rename = "Missions_TakedownsAfterTeleporting")]
    pub missions_takedowns_after_teleporting: Option<i64>,
    #[serde(rename = "VISION_CLEARED_PINGS")]
    pub vision_cleared_pings: Option<i64>,
    #[serde(rename = "WAS_LEAVER")]
    pub was_leaver: Option<i64>,
    #[serde(rename = "2026_S1A1_Skins_Jayce")]
    pub field_2026_s1_a1_skins_jayce: Option<i64>,
    #[serde(rename = "2026_S1A1_Skins_Yuumi")]
    pub field_2026_s1_a1_skins_yuumi: Option<i64>,
    #[serde(rename = "HoL_Elite_AsheCrystalArrowTakedowns")]
    pub ho_l_elite_ashe_crystal_arrow_takedowns: Option<i64>,
    #[serde(rename = "RIOT_ID_TAG_LINE")]
    pub riot_id_tag_line: Option<serde_json::Value>,
    #[serde(rename = "SUMMON_SPELL2_CAST")]
    pub summon_spell2_cast: Option<i64>,
    #[serde(rename = "PENTA_KILLS")]
    pub penta_kills: Option<i64>,
    #[serde(rename = "WARD_PLACED_DETECTOR")]
    pub ward_placed_detector: Option<i64>,
    #[serde(rename = "TIME_CCING_OTHERS")]
    pub time_ccing_others: Option<i64>,
    #[serde(rename = "TIME_OF_FROM_LAST_DISCONNECT")]
    pub time_of_from_last_disconnect: Option<i64>,
    #[serde(rename = "HoL_Elite_EzrealTrueshotBarrageMultiHit")]
    pub ho_l_elite_ezreal_trueshot_barrage_multi_hit: Option<i64>,
    #[serde(rename = "S3A2_PrismaticAug")]
    pub s3_a2_prismatic_aug: Option<i64>,
    #[serde(rename = "DOUBLE_KILLS")]
    pub double_kills: Option<i64>,
    #[serde(rename = "Missions_TakedownsWithHelpFromMonsters")]
    pub missions_takedowns_with_help_from_monsters: Option<i64>,
    #[serde(rename = "WeeklyMission_S2_SpiritPetals")]
    pub weekly_mission_s2_spirit_petals: Option<i64>,
    #[serde(rename = "Event_S1_A2_Arena_ReviveAllies")]
    pub event_s1_a2_arena_revive_allies: Option<i64>,
    #[serde(rename = "LARGEST_CRITICAL_STRIKE")]
    pub largest_critical_strike: Option<i64>,
    #[serde(rename = "2026_S1A1_Skins_Ashe")]
    pub field_2026_s1_a1_skins_ashe: Option<i64>,
    #[serde(rename = "PERK0")]
    pub perk0: Option<i64>,
    #[serde(rename = "TRUE_DAMAGE_DEALT_PLAYER")]
    pub true_damage_dealt_player: Option<i64>,
    #[serde(rename = "MAGIC_DAMAGE_TAKEN")]
    pub magic_damage_taken: Option<i64>,
    #[serde(rename = "CHAMPION_MISSION_STAT_1")]
    pub champion_mission_stat_1: Option<i64>,
    #[serde(rename = "WIN")]
    pub win: Option<String>,
    #[serde(rename = "PLAYER_POSITION")]
    pub player_position: Option<i64>,
    #[serde(rename = "Missions_LegendaryItems")]
    pub missions_legendary_items: Option<i64>,
    #[serde(rename = "HoL_EnemyTakedownUnderTower")]
    pub ho_l_enemy_takedown_under_tower: Option<i64>,
    #[serde(rename = "PLAYER_SCORE_6")]
    pub player_score_6: Option<i64>,
    #[serde(rename = "2026_S1A1_Skins_Seraphine")]
    pub field_2026_s1_a1_skins_seraphine: Option<i64>,
    #[serde(rename = "DemonsHand_MissionPointsE")]
    pub demons_hand_mission_points_e: Option<i64>,
    #[serde(rename = "Missions_PorosFed")]
    pub missions_poros_fed: Option<i64>,
    #[serde(rename = "Missions_TakedownsBefore15Min")]
    pub missions_takedowns_before15_min: Option<i64>,
    #[serde(rename = "PERK2")]
    pub perk2: Option<i64>,
    #[serde(rename = "TURRET_TAKEDOWNS")]
    pub turret_takedowns: Option<i64>,
    #[serde(rename = "Missions_ChampionsKilled")]
    pub missions_champions_killed: Option<i64>,
    #[serde(rename = "Event_S2A2_Exalted")]
    pub event_s2_a2_exalted: Option<i64>,
    #[serde(rename = "Missions_TakedownEpicMonstersSingleGame")]
    pub missions_takedown_epic_monsters_single_game: Option<i64>,
    #[serde(rename = "PERK1_VAR3")]
    pub perk1_var3: Option<i64>,
    #[serde(rename = "PERK5")]
    pub perk5: Option<i64>,
    #[serde(rename = "HoL_Elite_VayneTumbleDodge")]
    pub ho_l_elite_vayne_tumble_dodge: Option<i64>,
    #[serde(rename = "ON_MY_WAY_PINGS")]
    pub on_my_way_pings: Option<i64>,
    #[serde(rename = "Missions_TimeSpentActivelyPlaying")]
    pub missions_time_spent_actively_playing: Option<i64>,
    #[serde(rename = "PERK3_VAR1")]
    pub perk3_var1: Option<i64>,
    #[serde(rename = "LARGEST_MULTI_KILL")]
    pub largest_multi_kill: Option<i64>,
    #[serde(rename = "PERK2_VAR3")]
    pub perk2_var3: Option<i64>,
    #[serde(rename = "EXP")]
    pub exp: Option<i64>,
    #[serde(rename = "SPELL1_CAST")]
    pub spell1_cast: Option<i64>,
    #[serde(rename = "PHYSICAL_DAMAGE_DEALT_TO_CHAMPIONS")]
    pub physical_damage_dealt_to_champions: Option<i64>,
    #[serde(rename = "HOLD_PINGS")]
    pub hold_pings: Option<i64>,
    #[serde(rename = "ITEM4")]
    pub item4: Option<i64>,
    #[serde(rename = "PLAYERS_I_MUTED")]
    pub players_i_muted: Option<i64>,
    #[serde(rename = "Missions_ChampionTakedownsWithIgnite")]
    pub missions_champion_takedowns_with_ignite: Option<i64>,
    #[serde(rename = "Event_S1_A2_Mordekaiser")]
    pub event_s1_a2_mordekaiser: Option<i64>,
    #[serde(rename = "TRUE_DAMAGE_DEALT_TO_CHAMPIONS")]
    pub true_damage_dealt_to_champions: Option<i64>,
    #[serde(rename = "PHYSICAL_DAMAGE_TAKEN")]
    pub physical_damage_taken: Option<i64>,
    #[serde(rename = "VICTORY_POINT_TOTAL")]
    pub victory_point_total: Option<i64>,
    #[serde(rename = "TOTAL_DAMAGE_DEALT")]
    pub total_damage_dealt: Option<i64>,
    #[serde(rename = "Missions_ChampionTakedownsWhileGhosted")]
    pub missions_champion_takedowns_while_ghosted: Option<i64>,
    #[serde(rename = "2026_S1A1_Skins_Caitlyn")]
    pub field_2026_s1_a1_skins_caitlyn: Option<i64>,
    #[serde(rename = "HQ_TAKEDOWNS")]
    pub hq_takedowns: Option<i64>,
    #[serde(rename = "PERK3_VAR3")]
    pub perk3_var3: Option<i64>,
    #[serde(rename = "2026_S1A1_Skins_Yasuo")]
    pub field_2026_s1_a1_skins_yasuo: Option<i64>,
    #[serde(rename = "TEAM_POSITION")]
    pub team_position: Option<String>,
    #[serde(rename = "Event_ARAM_Docks")]
    pub event_aram_docks: Option<i64>,
    #[serde(rename = "PERK5_VAR3")]
    pub perk5_var3: Option<i64>,
    #[serde(rename = "HQ_KILLED")]
    pub hq_killed: Option<i64>,
    #[serde(rename = "DANGER_PINGS")]
    pub danger_pings: Option<i64>,
    #[serde(rename = "PLAYER_SCORE_8")]
    pub player_score_8: Option<i64>,
    #[serde(rename = "WARD_KILLED")]
    pub ward_killed: Option<i64>,
    #[serde(rename = "Event_S1_A2_Esports_TakedownEpicMonstersSingleGame")]
    pub event_s1_a2_esports_takedown_epic_monsters_single_game: Option<i64>,
    #[serde(rename = "CONSUMABLES_PURCHASED")]
    pub consumables_purchased: Option<i64>,
    #[serde(rename = "PLAYER_SCORE_0")]
    pub player_score_0: Option<i64>,
    #[serde(rename = "DRAGON_KILLS")]
    pub dragon_kills: Option<i64>,
    #[serde(rename = "Missions_TwoChampsKilledWithSameAbility")]
    pub missions_two_champs_killed_with_same_ability: Option<i64>,
    #[serde(rename = "VISION_WARDS_BOUGHT_IN_GAME")]
    pub vision_wards_bought_in_game: Option<i64>,
    #[serde(rename = "PLAYER_SCORE_1")]
    pub player_score_1: Option<i64>,
    #[serde(rename = "ITEM2")]
    pub item2: Option<i64>,
    #[serde(rename = "Event_S1_A1_AprilFools_Dragon")]
    pub event_s1_a1_april_fools_dragon: Option<i64>,
    #[serde(rename = "NODE_NEUTRALIZE")]
    pub node_neutralize: Option<i64>,
    #[serde(rename = "Missions_ChampionsHitWithAbilitiesEarlyGame")]
    pub missions_champions_hit_with_abilities_early_game: Option<i64>,
    #[serde(rename = "HoL_FightsSurvivedWhileLowHealth")]
    pub ho_l_fights_survived_while_low_health: Option<i64>,
    #[serde(rename = "ITEM3")]
    pub item3: Option<i64>,
    #[serde(rename = "TEAM_EARLY_SURRENDERED")]
    pub team_early_surrendered: Option<i64>,
    #[serde(rename = "SUMMONER_SPELL_1")]
    pub summoner_spell_1: Option<i64>,
    #[serde(rename = "BARON_KILLS")]
    pub baron_kills: Option<i64>,
    #[serde(rename = "SIGHT_WARDS_BOUGHT_IN_GAME")]
    pub sight_wards_bought_in_game: Option<i64>,
    #[serde(rename = "VISION_SCORE")]
    pub vision_score: Option<i64>,
    #[serde(rename = "Missions_SorceryRune")]
    pub missions_sorcery_rune: Option<i64>,
    #[serde(rename = "2026_S1A1_Skins_Briar")]
    pub field_2026_s1_a1_skins_briar: Option<i64>,
    #[serde(rename = "Missions_Crepe_SnowballLanded")]
    pub missions_crepe_snowball_landed: Option<i64>,
    #[serde(rename = "DemonsHand_MissionPointsB")]
    pub demons_hand_mission_points_b: Option<i64>,
    #[serde(rename = "PERK_PRIMARY_STYLE")]
    pub perk_primary_style: Option<i64>,
    #[serde(rename = "Event_Brawl_Minions")]
    pub event_brawl_minions: Option<i64>,
    #[serde(rename = "PERK1_VAR2")]
    pub perk1_var2: Option<i64>,
    #[serde(rename = "ENEMY_MISSING_PINGS")]
    pub enemy_missing_pings: Option<i64>,
    #[serde(rename = "TIME_PLAYED")]
    pub time_played: Option<i64>,
    #[serde(rename = "Event_S1_A2_AprilFools_Dragon")]
    pub event_s1_a2_april_fools_dragon: Option<i64>,
    #[serde(rename = "2026_S1A1_Skins_Lillia")]
    pub field_2026_s1_a1_skins_lillia: Option<i64>,
    #[serde(rename = "TOTAL_DAMAGE_DEALT_TO_OBJECTIVES")]
    pub total_damage_dealt_to_objectives: Option<i64>,
    #[serde(rename = "PLAYER_SUBTEAM_PLACEMENT")]
    pub player_subteam_placement: Option<i64>,
    #[serde(rename = "Missions_GoldFromStructuresDestroyed")]
    pub missions_gold_from_structures_destroyed: Option<i64>,
    #[serde(rename = "WAS_EARLY_SURRENDER_ACCOMPLICE")]
    pub was_early_surrender_accomplice: Option<i64>,
    #[serde(rename = "PERK3")]
    pub perk3: Option<i64>,
    #[serde(rename = "Event_S2A2Champ_DamageAutos")]
    pub event_s2_a2_champ_damage_autos: Option<i64>,
    #[serde(rename = "TOTAL_DAMAGE_SELF_MITIGATED")]
    pub total_damage_self_mitigated: Option<i64>,
    #[serde(rename = "PERK2_VAR1")]
    pub perk2_var1: Option<i64>,
    #[serde(rename = "Missions_VoidMitesSummoned")]
    pub missions_void_mites_summoned: Option<i64>,
    #[serde(rename = "Event_S2A2_MV")]
    pub event_s2_a2_mv: Option<i64>,
    #[serde(rename = "HoL_JungleCampsStolen")]
    pub ho_l_jungle_camps_stolen: Option<i64>,
    #[serde(rename = "MAGIC_DAMAGE_DEALT_PLAYER")]
    pub magic_damage_dealt_player: Option<i64>,
    #[serde(rename = "ActMission_S1_A2_FeatsOfStrength")]
    pub act_mission_s1_a2_feats_of_strength: Option<i64>,
    #[serde(rename = "ASSIST_ME_PINGS")]
    pub assist_me_pings: Option<i64>,
    #[serde(rename = "MUTED_ALL")]
    pub muted_all: Option<i64>,
    #[serde(rename = "NODE_CAPTURE_ASSIST")]
    pub node_capture_assist: Option<i64>,
    #[serde(rename = "ITEMS_PURCHASED")]
    pub items_purchased: Option<i64>,
    #[serde(rename = "LEVEL")]
    pub level: Option<i64>,
    #[serde(rename = "PERK0_VAR1")]
    pub perk0_var1: Option<i64>,
    #[serde(rename = "Missions_PrecisionRune")]
    pub missions_precision_rune: Option<i64>,
    #[serde(rename = "HoL_ShutdownGoldCollected")]
    pub ho_l_shutdown_gold_collected: Option<i64>,
    #[serde(rename = "GAME_ENDED_IN_EARLY_SURRENDER")]
    pub game_ended_in_early_surrender: Option<i64>,
    #[serde(rename = "WAS_AFK")]
    pub was_afk: Option<i64>,
    #[serde(rename = "NEUTRAL_MINIONS_KILLED_YOUR_JUNGLE")]
    pub neutral_minions_killed_your_jungle: Option<i64>,
    #[serde(rename = "CHAMPION_MISSION_STAT_3")]
    pub champion_mission_stat_3: Option<i64>,
    #[serde(rename = "SeasonalMissions_TakedownAtakhan")]
    pub seasonal_missions_takedown_atakhan: Option<i64>,
    #[serde(rename = "Missions_SnowballsHit")]
    pub missions_snowballs_hit: Option<i64>,
    #[serde(rename = "PERK4_VAR1")]
    pub perk4_var1: Option<i64>,
    #[serde(rename = "Missions_TakedownDragons")]
    pub missions_takedown_dragons: Option<i64>,
    #[serde(rename = "UNREAL_KILLS")]
    pub unreal_kills: Option<i64>,
    #[serde(rename = "Event_S1_A1_AprilFools_Snowball")]
    pub event_s1_a1_april_fools_snowball: Option<i64>,
    #[serde(rename = "TOTAL_TIME_CROWD_CONTROL_DEALT")]
    pub total_time_crowd_control_dealt: Option<i64>,
    #[serde(rename = "QUADRA_KILLS")]
    pub quadra_kills: Option<i64>,
    #[serde(rename = "Event_S1_A2_AprilFools_Garen_Play")]
    pub event_s1_a2_april_fools_garen_play: Option<i64>,
    #[serde(rename = "Missions_CreepScoreBy10Minutes")]
    pub missions_creep_score_by10_minutes: Option<i64>,
    #[serde(rename = "Missions_DamageToChampsWithItems")]
    pub missions_damage_to_champs_with_items: Option<i64>,
    #[serde(rename = "HoL_HiddenEnemiesDamaged")]
    pub ho_l_hidden_enemies_damaged: Option<i64>,
    #[serde(rename = "STAT_PERK_1")]
    pub stat_perk_1: Option<i64>,
    #[serde(rename = "HoL_ControlWardsKilled")]
    pub ho_l_control_wards_killed: Option<i64>,
    #[serde(rename = "RIOT_ID_GAME_NAME")]
    pub riot_id_game_name: Option<String>,
    #[serde(rename = "CHAMPIONS_KILLED")]
    pub champions_killed: Option<i64>,
    #[serde(rename = "PERK1_VAR1")]
    pub perk1_var1: Option<i64>,
    #[serde(rename = "PERK4_VAR3")]
    pub perk4_var3: Option<i64>,
    #[serde(rename = "S3A2_ZaahenUnlock")]
    pub s3_a2_zaahen_unlock: Option<i64>,
    #[serde(rename = "2026_S1A1_Skins_Camille")]
    pub field_2026_s1_a1_skins_camille: Option<i64>,
    #[serde(rename = "SUMMON_SPELL1_CAST")]
    pub summon_spell1_cast: Option<i64>,
    #[serde(rename = "SUMMONER_SPELL_2")]
    pub summoner_spell_2: Option<i64>,
    #[serde(rename = "Event_2025LR_StructuresEpicMonsters")]
    pub event_2025_lr_structures_epic_monsters: Option<i64>,
    #[serde(rename = "WeeklyMission_S2_FeatsOfStrength")]
    pub weekly_mission_s2_feats_of_strength: Option<i64>,
    #[serde(rename = "HoL_Elite_LucianCullingHits")]
    pub ho_l_elite_lucian_culling_hits: Option<i64>,
    #[serde(rename = "GET_BACK_PINGS")]
    pub get_back_pings: Option<i64>,
    #[serde(rename = "TEAM")]
    pub team: Option<i64>,
    #[serde(rename = "PLAYERS_THAT_MUTED_ME")]
    pub players_that_muted_me: Option<i64>,
    #[serde(rename = "ID")]
    pub id: Option<i64>,
    #[serde(rename = "TEAM_OBJECTIVE")]
    pub team_objective: Option<i64>,
    #[serde(rename = "TOTAL_DAMAGE_TAKEN")]
    pub total_damage_taken: Option<i64>,
    #[serde(rename = "ActMission_S1_A2_ArenaRoundsWon")]
    pub act_mission_s1_a2_arena_rounds_won: Option<i64>,
    #[serde(rename = "ITEM1")]
    pub item1: Option<i64>,
    #[serde(rename = "STAT_PERK_2")]
    pub stat_perk_2: Option<i64>,
    #[serde(rename = "PLAYER_SCORE_10")]
    pub player_score_10: Option<i64>,
    #[serde(rename = "2026_S1A1_Skins_Katarina")]
    pub field_2026_s1_a1_skins_katarina: Option<i64>,
    #[serde(rename = "WeeklyMission_S2_DamagingAbilities")]
    pub weekly_mission_s2_damaging_abilities: Option<i64>,
    #[serde(rename = "RETREAT_PINGS")]
    pub retreat_pings: Option<i64>,
    #[serde(rename = "PUUID")]
    pub puuid: Option<String>,
    #[serde(rename = "Missions_TrueDamageToStructures")]
    pub missions_true_damage_to_structures: Option<i64>,
    #[serde(rename = "GOLD_EARNED")]
    pub gold_earned: Option<i64>,
    #[serde(rename = "Event_ARAM_Hexgates")]
    pub event_aram_hexgates: Option<i64>,
    #[serde(rename = "HoL_SoloKills")]
    pub ho_l_solo_kills: Option<i64>,
    #[serde(rename = "HoL_TurretsTakenWithinMinutes")]
    pub ho_l_turrets_taken_within_minutes: Option<i64>,
    #[serde(rename = "2026_S1A1_Skins_Nautilus")]
    pub field_2026_s1_a1_skins_nautilus: Option<i64>,
    #[serde(rename = "KILLING_SPREES")]
    pub killing_sprees: Option<i64>,
    #[serde(rename = "MINIONS_KILLED")]
    pub minions_killed: Option<i64>,
    #[serde(rename = "ENEMY_VISION_PINGS")]
    pub enemy_vision_pings: Option<i64>,
    #[serde(rename = "HoL_Elite_LucianPiercingLightMultiHit")]
    pub ho_l_elite_lucian_piercing_light_multi_hit: Option<i64>,
    #[serde(rename = "Missions_PlaceUsefulWards")]
    pub missions_place_useful_wards: Option<i64>,
    #[serde(rename = "Missions_TakedownStructures")]
    pub missions_takedown_structures: Option<i64>,
    #[serde(rename = "LAST_TAKEDOWN_TIME")]
    pub last_takedown_time: Option<i64>,
    #[serde(rename = "PERK3_VAR2")]
    pub perk3_var2: Option<i64>,
    #[serde(rename = "PERK4")]
    pub perk4: Option<i64>,
    #[serde(rename = "STAT_PERK_0")]
    pub stat_perk_0: Option<i64>,
    #[serde(rename = "DemonsHand_MissionPointsA")]
    pub demons_hand_mission_points_a: Option<i64>,
    #[serde(rename = "TIME_SPENT_DISCONNECTED")]
    pub time_spent_disconnected: Option<i64>,
    #[serde(rename = "PERK2_VAR2")]
    pub perk2_var2: Option<i64>,
    #[serde(rename = "INDIVIDUAL_POSITION")]
    pub individual_position: Option<String>,
    #[serde(rename = "FRIENDLY_DAMPEN_LOST")]
    pub friendly_dampen_lost: Option<i64>,
    #[serde(rename = "HORDE_KILLS")]
    pub horde_kills: Option<i64>,
    #[serde(rename = "Missions_PlaceUsefulControlWards")]
    pub missions_place_useful_control_wards: Option<i64>,
    #[serde(rename = "PERK5_VAR1")]
    pub perk5_var1: Option<i64>,
    #[serde(rename = "SKIN")]
    pub skin: Option<String>,
    #[serde(rename = "NODE_CAPTURE")]
    pub node_capture: Option<i64>,
    #[serde(rename = "FRIENDLY_HQ_LOST")]
    pub friendly_hq_lost: Option<i64>,
    #[serde(rename = "Missions_InspirationRune")]
    pub missions_inspiration_rune: Option<i64>,
    #[serde(rename = "TOTAL_DAMAGE_SHIELDED_ON_TEAMMATES")]
    pub total_damage_shielded_on_teammates: Option<i64>,
    #[serde(rename = "WARD_PLACED")]
    pub ward_placed: Option<i64>,
    #[serde(rename = "ITEM5")]
    pub item5: Option<i64>,
    #[serde(rename = "PLAYER_SCORE_5")]
    pub player_score_5: Option<i64>,
    #[serde(rename = "HoL_Elite_EzrealEssenceFluxDetonated")]
    pub ho_l_elite_ezreal_essence_flux_detonated: Option<i64>,
    #[serde(rename = "Missions_PeriodicDamage")]
    pub missions_periodic_damage: Option<i64>,
    #[serde(rename = "NEUTRAL_MINIONS_KILLED")]
    pub neutral_minions_killed: Option<i64>,
    #[serde(rename = "2026_S1A1_SR_GrowthSmashed")]
    pub field_2026_s1_a1_sr_growth_smashed: Option<i64>,
    #[serde(rename = "BARRACKS_TAKEDOWNS")]
    pub barracks_takedowns: Option<i64>,
    #[serde(rename = "S3A1_PlayAsDemaciansOrAgainstNoxians")]
    pub s3_a1_play_as_demacians_or_against_noxians: Option<i64>,
    #[serde(rename = "TRUE_DAMAGE_TAKEN")]
    pub true_damage_taken: Option<i64>,
    #[serde(rename = "Missions_TakedownsAfterExhausting")]
    pub missions_takedowns_after_exhausting: Option<i64>,
    #[serde(rename = "BASIC_PINGS")]
    pub basic_pings: Option<i64>,
    #[serde(rename = "Event_S2A2Champ_DamageAbilities")]
    pub event_s2_a2_champ_damage_abilities: Option<i64>,
    #[serde(rename = "Missions_DamageToStructures")]
    pub missions_damage_to_structures: Option<i64>,
    #[serde(rename = "PLAYER_SCORE_3")]
    pub player_score_3: Option<i64>,
    #[serde(rename = "Missions_DominationRune")]
    pub missions_domination_rune: Option<i64>,
    #[serde(rename = "TOTAL_DAMAGE_DEALT_TO_BUILDINGS")]
    pub total_damage_dealt_to_buildings: Option<i64>,
    #[serde(rename = "PLAYER_AUGMENT_5")]
    pub player_augment_5: Option<i64>,
    #[serde(rename = "2026_S1A1_Skins_Samira")]
    pub field_2026_s1_a1_skins_samira: Option<i64>,
    #[serde(rename = "OBJECTIVES_STOLEN_ASSISTS")]
    pub objectives_stolen_assists: Option<i64>,
    #[serde(rename = "2026_S1A1_Skins_Poppy")]
    pub field_2026_s1_a1_skins_poppy: Option<i64>,
    #[serde(rename = "PLAYER_SCORE_2")]
    pub player_score_2: Option<i64>,
    #[serde(rename = "Event_S1_A2_AprilFools_Garen_Takedown")]
    pub event_s1_a2_april_fools_garen_takedown: Option<i64>,
    #[serde(rename = "FRIENDLY_TURRET_LOST")]
    pub friendly_turret_lost: Option<i64>,
    #[serde(rename = "PLAYER_SCORE_4")]
    pub player_score_4: Option<i64>,
    #[serde(rename = "Event_Brawl_Jungle")]
    pub event_brawl_jungle: Option<i64>,
    #[serde(rename = "Missions_Crepe_DamageDealtSpeedZone")]
    pub missions_crepe_damage_dealt_speed_zone: Option<i64>,
    #[serde(rename = "Missions_CannonMinionsKilled")]
    pub missions_cannon_minions_killed: Option<i64>,
    #[serde(rename = "PERK0_VAR3")]
    pub perk0_var3: Option<i64>,
    #[serde(rename = "HoL_Elite_VayneCondemnStun")]
    pub ho_l_elite_vayne_condemn_stun: Option<i64>,
    #[serde(rename = "DemonsHand_MissionPointsF")]
    pub demons_hand_mission_points_f: Option<i64>,
    #[serde(rename = "PLAYER_AUGMENT_1")]
    pub player_augment_1: Option<i64>,
    #[serde(rename = "TOTAL_DAMAGE_DEALT_TO_CHAMPIONS")]
    pub total_damage_dealt_to_champions: Option<i64>,
    #[serde(rename = "TOTAL_DAMAGE_DEALT_TO_EPIC_MONSTERS")]
    pub total_damage_dealt_to_epic_monsters: Option<i64>,
    #[serde(rename = "TOTAL_TIME_SPENT_DEAD")]
    pub total_time_spent_dead: Option<i64>,
    #[serde(rename = "TOTAL_HEAL_ON_TEAMMATES")]
    pub total_heal_on_teammates: Option<i64>,
    #[serde(rename = "DemonsHand_MissionPointsD")]
    pub demons_hand_mission_points_d: Option<i64>,
    #[serde(rename = "PLAYER_AUGMENT_4")]
    pub player_augment_4: Option<i64>,
    #[serde(rename = "WAS_AFK_AFTER_FAILED_SURRENDER")]
    pub was_afk_after_failed_surrender: Option<i64>,
    #[serde(rename = "PLAYER_AUGMENT_3")]
    pub player_augment_3: Option<i64>,
    #[serde(rename = "HoL_Elite_AsheHawkshotChampsRevealed")]
    pub ho_l_elite_ashe_hawkshot_champs_revealed: Option<i64>,
    #[serde(rename = "LARGEST_KILLING_SPREE")]
    pub largest_killing_spree: Option<i64>,
    #[serde(rename = "CHAMPION_TRANSFORM")]
    pub champion_transform: Option<i64>,
    #[serde(rename = "WAS_SURRENDER_DUE_TO_AFK")]
    pub was_surrender_due_to_afk: Option<i64>,
    #[serde(rename = "HoL_OutnumberedTakedowns")]
    pub ho_l_outnumbered_takedowns: Option<i64>,
    #[serde(rename = "Event_S1_A2_Arena_BraveryChampions")]
    pub event_s1_a2_arena_bravery_champions: Option<i64>,
    #[serde(rename = "Missions_DestroyPlants")]
    pub missions_destroy_plants: Option<i64>,
    #[serde(rename = "PLAYER_SCORE_7")]
    pub player_score_7: Option<i64>,
    #[serde(rename = "Missions_TotalGold")]
    pub missions_total_gold: Option<i64>,
    #[serde(rename = "Event_S2A2_PetalPoints")]
    pub event_s2_a2_petal_points: Option<i64>,
    #[serde(rename = "LARGEST_ABILITY_DAMAGE")]
    pub largest_ability_damage: Option<i64>,
    #[serde(rename = "HoL_ChampionsDamagedWhileHidden")]
    pub ho_l_champions_damaged_while_hidden: Option<i64>,
    #[serde(rename = "NAME")]
    pub name: Option<String>,
    #[serde(rename = "Missions_HealingFromLevelObjects")]
    pub missions_healing_from_level_objects: Option<i64>,
    #[serde(rename = "PERK1")]
    pub perk1: Option<i64>,
    #[serde(rename = "CHAMPION_MISSION_STAT_2")]
    pub champion_mission_stat_2: Option<i64>,
    #[serde(rename = "2026_S1A1_Skins_Galio")]
    pub field_2026_s1_a1_skins_galio: Option<i64>,
    #[serde(rename = "ITEM0")]
    pub item0: Option<i64>,
    #[serde(rename = "Missions_MinionsKilled")]
    pub missions_minions_killed: Option<i64>,
    #[serde(rename = "Missions_GoldPerMinute")]
    pub missions_gold_per_minute: Option<i64>,
    #[serde(rename = "ASSISTS")]
    pub assists: Option<i64>,
    #[serde(rename = "RIFT_HERALD_KILLS")]
    pub rift_herald_kills: Option<i64>,
    #[serde(rename = "SUMMONER_ID")]
    pub summoner_id: Option<i64>,
    #[serde(rename = "PLAYER_SCORE_9")]
    pub player_score_9: Option<i64>,
    #[serde(rename = "Missions_ResolveRune")]
    pub missions_resolve_rune: Option<i64>,
    #[serde(rename = "Missions_TakedownsUnderTurret")]
    pub missions_takedowns_under_turret: Option<i64>,
    #[serde(rename = "NUM_DEATHS")]
    pub num_deaths: Option<i64>,
    #[serde(rename = "TURRETS_KILLED")]
    pub turrets_killed: Option<i64>,
    #[serde(rename = "Missions_TakedownGold")]
    pub missions_takedown_gold: Option<i64>,
    #[serde(rename = "PERK_SUB_STYLE")]
    pub perk_sub_style: Option<i64>,
    #[serde(rename = "PHYSICAL_DAMAGE_DEALT_PLAYER")]
    pub physical_damage_dealt_player: Option<i64>,
    #[serde(rename = "KEYSTONE_ID")]
    pub keystone_id: Option<i64>,
    #[serde(rename = "NEED_VISION_PINGS")]
    pub need_vision_pings: Option<i64>,
    #[serde(rename = "CHAMPION_MISSION_STAT_0")]
    pub champion_mission_stat_0: Option<i64>,
    #[serde(rename = "TOTAL_TIME_CROWD_CONTROL_DEALT_TO_CHAMPIONS")]
    pub total_time_crowd_control_dealt_to_champions: Option<i64>,
    #[serde(rename = "PERK5_VAR2")]
    pub perk5_var2: Option<i64>,
    #[serde(rename = "Missions_TakedownWards")]
    pub missions_takedown_wards: Option<i64>,
    #[serde(rename = "PLAYER_SUBTEAM")]
    pub player_subteam: Option<i64>,
    #[serde(rename = "Missions_HexgatesUsed")]
    pub missions_hexgates_used: Option<i64>,
    #[serde(rename = "Event_S1_A2_AprilFools_Snowball")]
    pub event_s1_a2_april_fools_snowball: Option<i64>,
    #[serde(rename = "PLAYER_AUGMENT_2")]
    pub player_augment_2: Option<i64>,
    #[serde(rename = "Missions_TurretPlatesDestroyed")]
    pub missions_turret_plates_destroyed: Option<i64>,
    #[serde(rename = "Missions_CreepScore")]
    pub missions_creep_score: Option<i64>,
    #[serde(rename = "HoL_Elite_KaiSaAbilitiesUpgraded")]
    pub ho_l_elite_kai_sa_abilities_upgraded: Option<i64>,
    #[serde(rename = "SPELL4_CAST")]
    pub spell4_cast: Option<i64>,
    #[serde(rename = "PLAYER_ROLE")]
    pub player_role: Option<i64>,
    #[serde(rename = "SPELL3_CAST")]
    pub spell3_cast: Option<i64>,
    #[serde(rename = "Missions_GoldFromTurretPlatesTaken")]
    pub missions_gold_from_turret_plates_taken: Option<i64>,
    #[serde(rename = "COMMAND_PINGS")]
    pub command_pings: Option<i64>,
    #[serde(rename = "Missions_ImmobilizeChampions")]
    pub missions_immobilize_champions: Option<i64>,
    #[serde(rename = "Missions_TakedownBaronsElderDragons")]
    pub missions_takedown_barons_elder_dragons: Option<i64>,
    #[serde(rename = "2026_S1A1_Skins_Ornn")]
    pub field_2026_s1_a1_skins_ornn: Option<i64>,
    #[serde(rename = "ActMission_S1_A2_BloodyPetalsCollected")]
    pub act_mission_s1_a2_bloody_petals_collected: Option<i64>,
    #[serde(rename = "ITEM6")]
    pub item6: Option<i64>,
    #[serde(rename = "BARRACKS_KILLED")]
    pub barracks_killed: Option<i64>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Metadata {
    #[serde(rename = "gameLength")]
    pub game_length: u64,
    #[serde(rename = "lastGameChunkId")]
    pub last_game_chunk_id: u32,
    #[serde(rename = "lastKeyFrameId")]
    pub last_key_frame_id: u32,
    #[serde(rename = "statsJson")]
    pub stats_json: Vec<StatsJsonEntry>,
}
